dist: trusty
language: php

php:
  - 7.0
  - 7.1
  - 7.2

before_install:
  # use PHPUnit 6
  - rm ~/.phpenv/versions/$TRAVIS_PHP_VERSION/bin/phpunit
  - wget -O ~/.phpenv/versions/$TRAVIS_PHP_VERSION/bin/phpunit https://phar.phpunit.de/phpunit-6.phar
  - chmod +x ~/.phpenv/versions/$TRAVIS_PHP_VERSION/bin/phpunit

script: 
  - phpunit --bootstrap=modules/unittest/bootstrap.php modules/unittest/tests.php

notifications:
  email: false
